-- The authoritative schema now lives in supabase/migrations/.
-- Apply it with the Supabase CLI (`supabase db push`), the GitHub integration,
-- or by pasting the migration file into the SQL editor.
--
-- Current migration: migrations/20260715090000_epr_simplify.sql
