import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import { initDb } from './config/db.js';
import { authRouter } from './routes/authRoutes.js';
import { productRouter } from './routes/productRoutes.js';
import { libraryRouter } from './routes/libraryRoutes.js';
import { reportRouter } from './routes/reportRoutes.js';
dotenv.config();
initDb();
const app = express();
app.use(cors());
app.use(express.json());
app.get('/api/health', (_req,res)=>res.json({status:'ok'}));
app.use('/api/auth', authRouter);
app.use('/api/products', productRouter);
app.use('/api/library', libraryRouter);
app.use('/api/reports', reportRouter);
app.listen(process.env.PORT || 4000, ()=>console.log('API running'));
