-- Replace the shared packaging reference library (39 items), each carrying the
-- source of its weight. Run in the Supabase SQL editor. Personal items are not
-- touched.
--
--   derived   - recomputable from the dimensions on the row
--   published - a named published figure
--   estimate  - a starting figure with no published source
--
-- Weights are stored in grams.

begin;

delete from public.reference_library where user_id is null;

with v(name, material, ptype, len, wid, hei, wt, dens, notes, src) as (values
  ('Cardboard carton, small','Cardboard','primary',100,100,100,33.73,0.000033735,'Derived from dimensions. See the reference mark for the method.','{"kind":"derived","summary":"Calculated from this box’s own dimensions, not looked up.","detail":"Weight = blank area × board grammage. FEFCO 0201 blank = [2(L+W) + 40 mm joint] × (H + W). Board = 383 g/m² E flute, built from standard liners and 105 g/m² fluting with a 1.27 take-up factor. FEFCO puts industry-average board at 469-497 g/m². You can recompute this figure yourself from the dimensions shown.","publisher":"FEFCO","url":"https://www.fefco.org/lca/dscription-of-production-system/corrugated-board-production"}'),
  ('Cardboard carton, medium','Cardboard','primary',200,150,100,70.92,0.00002364,'Derived from dimensions. See the reference mark for the method.','{"kind":"derived","summary":"Calculated from this box’s own dimensions, not looked up.","detail":"Weight = blank area × board grammage. FEFCO 0201 blank = [2(L+W) + 40 mm joint] × (H + W). Board = 383 g/m² E flute, built from standard liners and 105 g/m² fluting with a 1.27 take-up factor. FEFCO puts industry-average board at 469-497 g/m². You can recompute this figure yourself from the dimensions shown.","publisher":"FEFCO","url":"https://www.fefco.org/lca/dscription-of-production-system/corrugated-board-production"}'),
  ('Cardboard carton, large','Cardboard','primary',300,200,150,139.54,0.000015504,'Derived from dimensions. See the reference mark for the method.','{"kind":"derived","summary":"Calculated from this box’s own dimensions, not looked up.","detail":"Weight = blank area × board grammage. FEFCO 0201 blank = [2(L+W) + 40 mm joint] × (H + W). Board = 383 g/m² E flute, built from standard liners and 105 g/m² fluting with a 1.27 take-up factor. FEFCO puts industry-average board at 469-497 g/m². You can recompute this figure yourself from the dimensions shown.","publisher":"FEFCO","url":"https://www.fefco.org/lca/dscription-of-production-system/corrugated-board-production"}'),
  ('Cardboard shipping case, small','Cardboard','secondary',250,180,120,119.56,0.00002214,'Derived from dimensions. See the reference mark for the method.','{"kind":"derived","summary":"Calculated from this box’s own dimensions, not looked up.","detail":"Weight = blank area × board grammage. FEFCO 0201 blank = [2(L+W) + 40 mm joint] × (H + W). Board = 443 g/m² B flute, built from standard liners and 105 g/m² fluting with a 1.36 take-up factor. FEFCO puts industry-average board at 469-497 g/m². You can recompute this figure yourself from the dimensions shown.","publisher":"FEFCO","url":"https://www.fefco.org/lca/dscription-of-production-system/corrugated-board-production"}'),
  ('Cardboard shipping case, medium','Cardboard','secondary',400,300,200,318.82,0.000013284,'Derived from dimensions. See the reference mark for the method.','{"kind":"derived","summary":"Calculated from this box’s own dimensions, not looked up.","detail":"Weight = blank area × board grammage. FEFCO 0201 blank = [2(L+W) + 40 mm joint] × (H + W). Board = 443 g/m² B flute, built from standard liners and 105 g/m² fluting with a 1.36 take-up factor. FEFCO puts industry-average board at 469-497 g/m². You can recompute this figure yourself from the dimensions shown.","publisher":"FEFCO","url":"https://www.fefco.org/lca/dscription-of-production-system/corrugated-board-production"}'),
  ('Cardboard shipping case, large','Cardboard','secondary',550,400,300,601.32,0.000009111,'Derived from dimensions. See the reference mark for the method.','{"kind":"derived","summary":"Calculated from this box’s own dimensions, not looked up.","detail":"Weight = blank area × board grammage. FEFCO 0201 blank = [2(L+W) + 40 mm joint] × (H + W). Board = 443 g/m² B flute, built from standard liners and 105 g/m² fluting with a 1.36 take-up factor. FEFCO puts industry-average board at 469-497 g/m². You can recompute this figure yourself from the dimensions shown.","publisher":"FEFCO","url":"https://www.fefco.org/lca/dscription-of-production-system/corrugated-board-production"}'),
  ('Cardboard transit case, small','Cardboard','tertiary',600,400,400,1171.69,0.000012205,'Derived from dimensions. See the reference mark for the method.','{"kind":"derived","summary":"Calculated from this box’s own dimensions, not looked up.","detail":"Weight = blank area × board grammage. FEFCO 0201 blank = [2(L+W) + 40 mm joint] × (H + W). Board = 718 g/m² BC flute, built from standard liners and 105 g/m² fluting with a 1.36 take-up factor. FEFCO puts industry-average board at 469-497 g/m². You can recompute this figure yourself from the dimensions shown.","publisher":"FEFCO","url":"https://www.fefco.org/lca/dscription-of-production-system/corrugated-board-production"}'),
  ('Cardboard transit case, medium','Cardboard','tertiary',800,600,500,2242.88,0.000009345,'Derived from dimensions. See the reference mark for the method.','{"kind":"derived","summary":"Calculated from this box’s own dimensions, not looked up.","detail":"Weight = blank area × board grammage. FEFCO 0201 blank = [2(L+W) + 40 mm joint] × (H + W). Board = 718 g/m² BC flute, built from standard liners and 105 g/m² fluting with a 1.36 take-up factor. FEFCO puts industry-average board at 469-497 g/m². You can recompute this figure yourself from the dimensions shown.","publisher":"FEFCO","url":"https://www.fefco.org/lca/dscription-of-production-system/corrugated-board-production"}'),
  ('Cardboard pallet box, large','Cardboard','tertiary',1200,1000,800,5737.86,0.000005977,'Derived from dimensions. See the reference mark for the method.','{"kind":"derived","summary":"Calculated from this box’s own dimensions, not looked up.","detail":"Weight = blank area × board grammage. FEFCO 0201 blank = [2(L+W) + 40 mm joint] × (H + W). Board = 718 g/m² BC flute, built from standard liners and 105 g/m² fluting with a 1.36 take-up factor. FEFCO puts industry-average board at 469-497 g/m². You can recompute this figure yourself from the dimensions shown.","publisher":"FEFCO","url":"https://www.fefco.org/lca/dscription-of-production-system/corrugated-board-production"}'),
  ('Paper bag, small','Paper','primary',180,80,220,11.59,0.000003659,'Derived from dimensions. See the reference mark for the method.','{"kind":"derived","summary":"Calculated from this item’s own dimensions, not looked up.","detail":"Weight = surface area × 90 g/m² kraft paper. Recompute from the dimensions shown if your paper grade differs."}'),
  ('Paper bag, medium','Paper','primary',260,120,320,24.7,0.000002474,'Derived from dimensions. See the reference mark for the method.','{"kind":"derived","summary":"Calculated from this item’s own dimensions, not looked up.","detail":"Weight = surface area × 90 g/m² kraft paper. Recompute from the dimensions shown if your paper grade differs."}'),
  ('Paper bag, large','Paper','primary',320,160,420,40.9,0.000001902,'Derived from dimensions. See the reference mark for the method.','{"kind":"derived","summary":"Calculated from this item’s own dimensions, not looked up.","detail":"Weight = surface area × 90 g/m² kraft paper. Recompute from the dimensions shown if your paper grade differs."}'),
  ('Paper wrap sheet, small','Paper','secondary',500,500,1,17.5,0.00007,'Derived from dimensions. See the reference mark for the method.','{"kind":"derived","summary":"Calculated from this item’s own dimensions, not looked up.","detail":"Weight = surface area × 70 g/m² kraft paper. Recompute from the dimensions shown if your paper grade differs."}'),
  ('Paper wrap sheet, medium','Paper','secondary',750,750,1,39.38,0.00007,'Derived from dimensions. See the reference mark for the method.','{"kind":"derived","summary":"Calculated from this item’s own dimensions, not looked up.","detail":"Weight = surface area × 70 g/m² kraft paper. Recompute from the dimensions shown if your paper grade differs."}'),
  ('Paper wrap sheet, large','Paper','secondary',1000,1000,1,70,0.00007,'Derived from dimensions. See the reference mark for the method.','{"kind":"derived","summary":"Calculated from this item’s own dimensions, not looked up.","detail":"Weight = surface area × 70 g/m² kraft paper. Recompute from the dimensions shown if your paper grade differs."}'),
  ('PET bottle 500 ml','Plastic','primary',65,65,220,14,0.000015062,'Estimate only. See the reference mark before relying on it.','{"kind":"estimate","summary":"Estimate. No published source behind this figure.","detail":"A realistic starting figure for a 500 ml PET drinks bottle. Assumes a standard, non-lightweighted bottle. Replace it with your supplier’s specification sheet before you submit EPR data, since estimates are not evidence."}'),
  ('PET bottle 1 L','Plastic','primary',80,80,280,22,0.000012277,'Estimate only. See the reference mark before relying on it.','{"kind":"estimate","summary":"Estimate. No published source behind this figure.","detail":"A realistic starting figure for a 1 litre PET bottle. Assumes a standard, non-lightweighted bottle. Replace it with your supplier’s specification sheet before you submit EPR data, since estimates are not evidence."}'),
  ('PET bottle 2 L','Plastic','primary',100,100,320,35,0.000010937,'Estimate only. See the reference mark before relying on it.','{"kind":"estimate","summary":"Estimate. No published source behind this figure.","detail":"A realistic starting figure for a 2 litre PET bottle. Assumes a standard, non-lightweighted bottle. Replace it with your supplier’s specification sheet before you submit EPR data, since estimates are not evidence."}'),
  ('Polythene mailer, small','Plastic','secondary',250,180,5,8,0.000035556,'Estimate only. See the reference mark before relying on it.','{"kind":"estimate","summary":"Estimate. No published source behind this figure.","detail":"A realistic starting figure for a small co-extruded courier mailer. Assumes roughly 60 micron co-extruded film. Replace it with your supplier’s specification sheet before you submit EPR data, since estimates are not evidence."}'),
  ('Polythene mailer, medium','Plastic','secondary',350,250,5,15,0.000034286,'Estimate only. See the reference mark before relying on it.','{"kind":"estimate","summary":"Estimate. No published source behind this figure.","detail":"A realistic starting figure for a medium co-extruded courier mailer. Assumes roughly 60 micron co-extruded film. Replace it with your supplier’s specification sheet before you submit EPR data, since estimates are not evidence."}'),
  ('Polythene mailer, large','Plastic','secondary',450,350,5,25,0.000031746,'Estimate only. See the reference mark before relying on it.','{"kind":"estimate","summary":"Estimate. No published source behind this figure.","detail":"A realistic starting figure for a large co-extruded courier mailer. Assumes roughly 60 micron co-extruded film. Replace it with your supplier’s specification sheet before you submit EPR data, since estimates are not evidence."}'),
  ('Pallet stretch wrap, half pallet','Plastic','tertiary',800,600,800,120,3.13e-7,'Estimate only. See the reference mark before relying on it.','{"kind":"estimate","summary":"Estimate. No published source behind this figure.","detail":"A realistic starting figure for stretch wrap on a half pallet load. Wrap weight varies widely with film gauge and number of turns. Replace it with your supplier’s specification sheet before you submit EPR data, since estimates are not evidence."}'),
  ('Pallet stretch wrap, full pallet','Plastic','tertiary',1200,1000,1200,220,1.53e-7,'Estimate only. See the reference mark before relying on it.','{"kind":"estimate","summary":"Estimate. No published source behind this figure.","detail":"A realistic starting figure for stretch wrap on a standard pallet load. Wrap weight varies widely with film gauge and number of turns. Replace it with your supplier’s specification sheet before you submit EPR data, since estimates are not evidence."}'),
  ('Pallet stretch wrap, tall pallet','Plastic','tertiary',1200,1000,1800,320,1.48e-7,'Estimate only. See the reference mark before relying on it.','{"kind":"estimate","summary":"Estimate. No published source behind this figure.","detail":"A realistic starting figure for stretch wrap on a tall pallet load. Wrap weight varies widely with film gauge and number of turns. Replace it with your supplier’s specification sheet before you submit EPR data, since estimates are not evidence."}'),
  ('Glass jar 100 ml','Glass','primary',55,55,80,110,0.000454545,'Estimate only. See the reference mark before relying on it.','{"kind":"estimate","summary":"Estimate. No published source behind this figure.","detail":"A realistic starting figure for a 100 ml container glass jar. Glass weights vary a lot between standard and lightweighted ranges. Replace it with your supplier’s specification sheet before you submit EPR data, since estimates are not evidence."}'),
  ('Glass bottle 500 ml','Glass','primary',65,65,230,300,0.000308721,'Estimate only. See the reference mark before relying on it.','{"kind":"estimate","summary":"Estimate. No published source behind this figure.","detail":"A realistic starting figure for a 500 ml container glass bottle. Glass weights vary a lot between standard and lightweighted ranges. Replace it with your supplier’s specification sheet before you submit EPR data, since estimates are not evidence."}'),
  ('Glass bottle 750 ml','Glass','primary',75,75,300,450,0.000266667,'Estimate only. See the reference mark before relying on it.','{"kind":"estimate","summary":"Estimate for a standard-weight bottle. A published lightweight figure exists.","detail":"Assumes a standard 750 ml wine bottle. British Glass reports the lightest UK 70 cl round at 340 g, and says average bottle weight has fallen about 40% in 15 years through rightweighting. If your bottles are a lightweighted range, use a lower figure and your supplier’s spec.","publisher":"British Glass","url":"https://britglass.org.uk/knowledge-base/digital-library-and-information-services/lighter-bottles-use-less-glass"}'),
  ('Aluminium can 150 ml','Aluminium','primary',53,53,110,10,0.000032364,'Estimate only. See the reference mark before relying on it.','{"kind":"estimate","summary":"Estimate. No published source behind this figure.","detail":"A realistic starting figure for a 150 ml slimline beverage can. Scaled down from the published 500 ml can weight. Replace it with your supplier’s specification sheet before you submit EPR data, since estimates are not evidence."}'),
  ('Aluminium can 330 ml','Aluminium','primary',66,66,115,13,0.000025951,'Estimate only. See the reference mark before relying on it.','{"kind":"estimate","summary":"Estimate. No published source behind this figure.","detail":"A realistic starting figure for a 330 ml beverage can. Sits between the published 500 ml can weight and the industry’s stated 10 g target. Replace it with your supplier’s specification sheet before you submit EPR data, since estimates are not evidence."}'),
  ('Aluminium can 500 ml','Aluminium','primary',66,66,168,16,0.000021864,'Published figure. See the reference mark for the source.','{"kind":"published","summary":"Published figure from the metal packaging industry body.","detail":"Metal Packaging Europe reports a 500 ml aluminium beverage can at around 16 g, against about 30 g for the steel equivalent, and notes can makers have cut metal use by roughly 50% over 40 years.","publisher":"Metal Packaging Europe","url":"https://www.metalpackagingeurope.org/news/can-logistics-lighter-greener-and-more-efficient/"}'),
  ('Steel food tin, small','Steel','primary',73,73,58,35,0.000113239,'Estimate only. See the reference mark before relying on it.','{"kind":"estimate","summary":"Estimate. No published source behind this figure.","detail":"A realistic starting figure for a 200 ml steel food can. Food cans are heavier per volume than beverage cans. Replace it with your supplier’s specification sheet before you submit EPR data, since estimates are not evidence."}'),
  ('Steel food tin, medium','Steel','primary',73,73,110,60,0.000102356,'Estimate only. See the reference mark before relying on it.','{"kind":"estimate","summary":"Estimate. No published source behind this figure.","detail":"A realistic starting figure for a 400 ml steel food can. Food cans are heavier per volume than beverage cans. Replace it with your supplier’s specification sheet before you submit EPR data, since estimates are not evidence."}'),
  ('Steel paint tin 2.5 L','Steel','primary',155,155,175,300,0.000071354,'Estimate only. See the reference mark before relying on it.','{"kind":"estimate","summary":"Estimate. No published source behind this figure.","detail":"A realistic starting figure for a 2.5 litre steel paint tin. Assumes a lever-lid tin with a heavier gauge body. Replace it with your supplier’s specification sheet before you submit EPR data, since estimates are not evidence."}'),
  ('Wooden crate, small','Wood','tertiary',400,300,200,2000,0.000083333,'Estimate only. See the reference mark before relying on it.','{"kind":"estimate","summary":"Estimate. No published source behind this figure.","detail":"A realistic starting figure for a small softwood crate. Timber weight swings with species and moisture content. Replace it with your supplier’s specification sheet before you submit EPR data, since estimates are not evidence."}'),
  ('Euro pallet','Wood','tertiary',1200,800,144,25000,0.000180845,'Published figure. See the reference mark for the source.','{"kind":"published","summary":"Published specification from the pallet standards body.","detail":"EPAL specifies the EPAL Euro pallet (EPAL 1) at 1200 × 800 × 144 mm weighing approximately 25 kg, with a 1,500 kg safe working load. The dimensions and weight on this row match that specification exactly.","publisher":"EPAL","url":"https://www.epal-pallets.org/eu-en/load-carriers/epal-euro-pallet"}'),
  ('Wooden crate, large','Wood','tertiary',1200,1000,800,35000,0.000036458,'Estimate only. See the reference mark before relying on it.','{"kind":"estimate","summary":"Estimate. No published source behind this figure.","detail":"A realistic starting figure for a large softwood transit crate. Timber weight swings with species and moisture content. Replace it with your supplier’s specification sheet before you submit EPR data, since estimates are not evidence."}'),
  ('Mixed material pack, small','Other','primary',150,100,50,30,0.00004,'Estimate only. See the reference mark before relying on it.','{"kind":"estimate","summary":"Estimate. No published source behind this figure.","detail":"A realistic starting figure for a small mixed material pack. A placeholder for packs that do not fit one material. Split it into single-material layers where you can. Replace it with your supplier’s specification sheet before you submit EPR data, since estimates are not evidence."}'),
  ('Mixed material pack, medium','Other','secondary',350,250,150,120,0.000009143,'Estimate only. See the reference mark before relying on it.','{"kind":"estimate","summary":"Estimate. No published source behind this figure.","detail":"A realistic starting figure for a medium mixed material pack. A placeholder for packs that do not fit one material. Split it into single-material layers where you can. Replace it with your supplier’s specification sheet before you submit EPR data, since estimates are not evidence."}'),
  ('Mixed material pack, large','Other','tertiary',800,600,400,600,0.000003125,'Estimate only. See the reference mark before relying on it.','{"kind":"estimate","summary":"Estimate. No published source behind this figure.","detail":"A realistic starting figure for a large mixed material pack. A placeholder for packs that do not fit one material. Split it into single-material layers where you can. Replace it with your supplier’s specification sheet before you submit EPR data, since estimates are not evidence."}')
), g as (select gen_random_uuid() as id, v.* from v)
insert into public.reference_library(id, user_id, payload)
select g.id, null, jsonb_build_object(
  'id', g.id, 'referenceName', g.name, 'materialType', g.material,
  'packagingType', g.ptype, 'length', g.len, 'width', g.wid, 'height', g.hei,
  'unit', 'mm', 'averageWeight', g.wt, 'densityValue', g.dens, 'notes', g.notes,
  'source', g.src::jsonb)
from g;

delete from public.hidden_default_items h
where not exists (select 1 from public.reference_library r where r.id = h.item_id);

commit;
